version: '3.8'

services:
  # mongo db
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # FastAPI 
  app:
    build: .
    container_name: fast_api_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
    env_file:
      - .env
    environment:
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb

volumes:
  mongo_data: